### ISSUE TITLE
CSV data for Jobs page

### ISSUE THREAD

**Issue by srid** [fpindia/fpindia-site#10]
We basically want to port https://github.com/fpindia/jobs to this site.

- Read from `.csv` files and build the model value
- Render the jobs page using the model

(Could even happen as a separate site, in a separate repo, if desired; cc @ajnsit)

Mentorship note: I think we could do pair programming here so that I can demonstrate to others how `Dynamic` (and `UnionMount`) in Ema works, and more generally how to write static sites like this.

**Tasks**

- [x] Srid: add the basic infrastructure
- [ ] Fill in the rest of CSV types

**Comment by srid** [comment]
@ajnsit I'm not clear on the jobs CSV thing, so I have a number of questions.

I see markdown formatted columns in https://github.com/fpindia/jobs/blob/main/raw/active.csv - what's the reason for this?

What Haskell datatype do you want this CSV encoded into? Do we change the CSV format?  For example, does it really have to contain Markdown? Or can we split the text and URL into separate columns? Why is `closed.csv` a separate file, instead of reusing the 'active' column in `active.csv?

**Comment by ajnsit** [comment]
> I see markdown formatted columns in https://github.com/fpindia/jobs/blob/main/raw/active.csv - what's the reason for this?

That's just bad design on my part. We can change to separate columns for the link and the title.

>  What Haskell datatype do you want this CSV encoded into?

How about something like the following -

```haskell
data Row = Row
  { name :: String
  , website :: URL
  , source :: Source
  , location :: Place
  , languages :: [Language]
  , permalink :: String
  , active :: Boolean
  }

data Source = Source { sourceType :: SourceType, sourceUrl :: URL }
data SourceType = Reddit | Github | Twitter | LinkedIn | OtherJobSite | OtherForum | OtherSourceType
-- Some languages of the top of my head, we can add more
data Language = Haskell | PureScript | Erlang | Agda | Idris | OtherLanguage String
```

> Do we change the CSV format? For example, does it really have to contain Markdown? Or can we split the text and URL into separate columns?

Yes, separate columns is better.

> Why is closed.csv a separate file, instead of reusing the 'Status' column in active.csv?

This is mostly for historical reasons. We had only the separate markdown files in the past, and I didn't want to clutter the active jobs page with the old jobs. The same structure was kept when I added csv files as the source of truth. I think we should move to a single CSV file now.

**Comment by udaycruise2903** [comment]
@srid Yes, I am picking up this task
