### ISSUE TITLE
Add color palette to site

### ISSUE THREAD

**Issue by CaptainLazarus** [fpindia/fpindia-site#13]
The agreed upon color palette is Rose 300 + Cyan 900 (Refer to tailwind inbuilt colors for specifications). 

Rose 300 + Dark Text (Preferably Black)
Cyan 900 + White Text

**Comment by srid** [comment]
d10253f87efff7f77c5609f9bc9bf0f59c6ce782 likely undid some of the colors you were planning to use. Sorry about that. Feel free to revert this commit if you'd like.

**Comment by srid** [comment]
I think this issue is out of date after @ajnsit 's redesign. Re-open if still relevant!
