### ISSUE TITLE
Mobile friendly view

### ISSUE THREAD

**Issue by srid** [fpindia/fpindia-site#30]
The site doesn't look good on mobile. Tailwind provides classes to conditionally set styles based on screen size. We should use that.

https://tailwindcss.com/docs/responsive-design

**Comment by srid** [comment]
After #31, on mobile, we now see this, but the burger icon is not clickable.

<img width="186" alt="image" src="https://user-images.githubusercontent.com/3998/183674668-ae916b37-dab3-42e8-9469-7aa975409fd4.png">

**Comment by ajnsit** [comment]
@srid Yeah, I added the header menu for small screens, but it's still not complete. I need to add some Javascript to enable the menu to show up.

**Comment by srid** [comment]
Looks like this has been done now.
